server:
  port: 9001
  shutdown: graceful

spring:
    # config:
    #     activate:
    #       on-profile: local
          
    data:
      mongodb:
        host: localhost
        port: 27017
        database: admin
        # username: act_user
        # password: hihihihihihi

        # spring.data.mongodb.uri=mongodb://[ip 정보]:[port 정보]
        # spring.data.mongodb.database=[데이터베이스 이름]
        # mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
