server:
  port: 9091

spring:
  application:
    name: database

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/maria
    username: "taylee"
    password: "new1234!"

  jpa:
    hibernate:
      ddl-auto: update #create? ?? ? ?????? ?? Table? ??????.