server:
  port: 9003
  shutdown: graceful

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: urlDomain
  kafka:
    bootstrap-servers: www.taylee.link:9003

kafka:
  server: www.taylee.link
  port: 9003