server:
  port: 9090

spring:
  application:
    name: database

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/maria
    username: taylee
    password: "*********"

  jpa:
    hibernate:
      ddl-auto: update #create? ?? ? ?????? ?? Table? ??????.

eureka:
  client:
    register-with-eurka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka