server:
  port: 9093

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git: #?? ?? ??? git: {??} ????? ??? ??? ?.
          uri: https://github.com/taehyuklee/configServer #config server? yml???? ??? repository
          default-label: main #repository? branch?? - main
        encrypt:
          enabled: false #?? ????? ??? ????.

#actuator ??
management:
  endpoints:
    web:
      exposure:
        include: "*" #?? ??? ????? (actuator)

  endpoint:
    shutdown:
      enable: true

encrypt:
  key: taehyuk's-key #??? ???? ???? Key? (postman?? encrypt, decrypt?? ???)