server:
  port: 9003
  shutdown: graceful

# spring:

#h2 setting
#   h2:
#     console:
#       enabled: true
#       path: /h2-console
#   datasource:
#     hikari:
#       jdbc-url: jdbc:h2:tcp://localhost/~/DB
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: swaggerStorage
  servelet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
      enabled: true
