server:
  port: 9001

spring:
  application:
    name: database

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/maria
    username: taylee #그냥 막 사용하는 username, password
    password: new1234!

  jpa:
    hibernate:
      ddl-auto: update #create? ?? ? ?????? ?? Table? ??????.
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace