spring:

#h2 setting
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/DB
    driver-class-name: org.h2.Driver
    username: sa
    password:

#Postgresql setting
    # datasource:
    #     driver-class-name: org.postgresql.Driver
    #     url: jdbc:postgresql://localhost:5432/practice
    #     username: postgres
    #     password: 1234
    
